# Restaurant Intelligence KPI Measures

## Overview

Restaurant Intelligence KPIs provide visibility into restaurant performance, revenue contribution, operational efficiency, and marketplace analytics.

These measures support:

- Restaurant Performance Dashboard
- Marketplace Intelligence
- Vendor Performance Monitoring
- Revenue Contribution Analysis
- Executive Reporting

Display Folder:

```text
Restaurant KPIs
```

---

# 1. Total Restaurants

## DAX

```DAX
Total Restaurants =
DISTINCTCOUNT (
    dim_restaurants[restaurant_key]
)
```

## Business Purpose

Measures total restaurants available on the platform.

Used for:

- Marketplace Monitoring
- Capacity Analysis

---

# 2. Active Restaurants

## DAX

```DAX
Active Restaurants =
DISTINCTCOUNT (
    fact_orders[restaurant_key]
)
```

## Business Purpose

Measures restaurants receiving orders.

Used for:

- Marketplace Activity Monitoring
- Restaurant Engagement Analysis

---

# 3. Revenue Per Restaurant

## DAX

```DAX
Revenue Per Restaurant =
DIVIDE (
    [Total Revenue],
    [Active Restaurants]
)
```

## Business Purpose

Measures average revenue generated by restaurants.

Used for:

- Marketplace Efficiency
- Revenue Productivity

---

# 4. Average Restaurant Rating

## DAX

```DAX
Average Restaurant Rating =
AVERAGE (
    dim_restaurants[average_rating]
)
```

## Business Purpose

Measures overall restaurant quality.

Used for:

- Customer Experience Analysis
- Vendor Quality Monitoring

---

# 5. Average Restaurant Delivery Time

## DAX

```DAX
Average Restaurant Delivery Time =
AVERAGE (
    dim_restaurants[estimated_delivery_time]
)
```

## Business Purpose

Measures average expected delivery duration.

Used for:

- Operational Planning
- Customer Experience Monitoring

---

# 6. Restaurant Revenue Contribution %

## DAX

```DAX
Restaurant Revenue Contribution % =
DIVIDE (
    [Total Revenue],
    CALCULATE (
        [Total Revenue],
        ALL ( dim_restaurants )
    )
)
```

## Format

```text
Percentage
2 Decimal Places
```

## Business Purpose

Measures revenue contribution by restaurant.

Used for:

- Top Performer Analysis
- Revenue Concentration Analysis

---

# 7. Revenue Rank

## DAX

```DAX
Revenue Rank =
RANKX (
    ALL ( dim_restaurants[restaurant_name] ),
    [Total Revenue],
    ,
    DESC
)
```

## Business Purpose

Ranks restaurants by revenue.

Used for:

- Top Restaurant Analysis
- Executive Reporting

---

# 8. Orders Per Restaurant

## DAX

```DAX
Orders Per Restaurant =
DIVIDE (
    [Total Orders],
    [Active Restaurants]
)
```

## Business Purpose

Measures average order volume per restaurant.

Used for:

- Marketplace Productivity Analysis

---

# 9. Average Customer Rating By Restaurant

## DAX

```DAX
Average Customer Rating By Restaurant =
AVERAGE (
    fact_orders[service_rating]
)
```

## Business Purpose

Measures restaurant customer satisfaction.

Used for:

- Restaurant Performance Evaluation

---

# 10. Restaurant Performance Score

## DAX

```DAX
Restaurant Performance Score =
(
    DIVIDE (
        [Average Customer Rating By Restaurant],
        5
    ) * 0.4
)
+
(
    DIVIDE (
        [Revenue Per Restaurant],
        [Total Revenue]
    ) * 0.6
)
```

## Format

```text
Percentage
2 Decimal Places
```

## Business Purpose

Composite restaurant performance indicator.

Used for:

- Vendor Benchmarking
- Marketplace Optimization

---

# Restaurant KPI Summary

| KPI | Purpose |
|------|----------|
| Total Restaurants | Marketplace size |
| Active Restaurants | Marketplace activity |
| Revenue Per Restaurant | Revenue productivity |
| Average Restaurant Rating | Vendor quality |
| Average Restaurant Delivery Time | Operational benchmark |
| Restaurant Revenue Contribution % | Revenue concentration |
| Revenue Rank | Restaurant ranking |
| Orders Per Restaurant | Productivity |
| Average Customer Rating By Restaurant | Customer experience |
| Restaurant Performance Score | Composite benchmark |

---

# Semantic Model Structure

```text
_MEASURES

├── Executive KPIs
├── Revenue KPIs
├── Operations KPIs
├── Customer KPIs
│
└── Restaurant KPIs
    ├── Total Restaurants
    ├── Active Restaurants
    ├── Revenue Per Restaurant
    ├── Average Restaurant Rating
    ├── Average Restaurant Delivery Time
    ├── Restaurant Revenue Contribution %
    ├── Revenue Rank
    ├── Orders Per Restaurant
    ├── Average Customer Rating By Restaurant
    └── Restaurant Performance Score
```
